### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by davidmoten** [EdwardRaff/JSAT#2]
Hi, crazy library, I can't believe how much stuff you've implemented yourself. Must have been terrific for understanding all these algorithms.

I'm new to ML and am struggling to find pure java machine learning libraries. JSAT seems to fit the bill but testing seems thin on the ground in places. What is your impression of the reliability of the classifiers for instance? I was going to start with a DecisionTree but find no tests thus sample code and am curious as to how healthy you think this classifier is. 

In general do you suggest that this library is ready for use in a production environment? If you have doubts in what areas and would you mind documenting this in the README?

Thanks!

**Comment by EdwardRaff** [comment]
Hi david, thanks for asking! It was also fun :) 

JSAT is *not* as heavily used as many other machine learning libraries, so there will always be a lesser confidence in bug free code. And if there is a bug I will certainly work to fix it, but this isn't my full time job - so I can't provide any *real* support and I don't have a large number of colleges working on it as well, so fixes could certainly take longer. 

That said, I know of a few instances where JSAT is being used in production today, and a few start ups have used it as well. 

In general, if you encounter any bugs they will *probably be in the training process*, rather than the prediction process. Since you don't generally do training in a production system, but deploy already trained models to the system, that does make it considerably safer to rely on -  as the prediction code is almost always much simpler. If you encounter a bug during training, then you just don't update the model. 

That being said, of the Java libraries for ML, the only 3 I'm really aware of are Weka, JavaML, and my own. JavaML stopped being updated a few years ago, and in my own personal experience JSAT has fewer bugs (mostly issues of numerical stability) than Weka. If you *need* support though, you can buy support for Weka. 

And obviously, part of the GPL is that this comes with no warranty or guarantee of correctness ;)

**Comment by davidmoten** [comment]
Thanks Edward for your detailed response. 

You make a great point about the training process. Whatever the training process comes up with it's totally up to me to accept it according on the model accuracy against a test data set. 

I plugged away yesterday and saw that it was way easier than I had thought to use the Apache Spark ML libraries. Quick test app is [here](https://github.com/amsa-code/risky/blob/master/spark/src/main/java/MLApp.java) if you are interested. As this is or will be a path well-trodden it's probably a good way for me to go for the moment. Thanks anyway for your contributions in ML and I will no doubt return to the library for ML and other algorithmic goodness. 

By the way I see why tests are skipped by default! They took 3.5 hours to run on my crappy laptop. I also ran cobertura plugin to see what test coverage was like which was interesting. Have you run that yourself? Might be worth publishing on your github.io repo pointed to by JSAT readme as an indicator of how tested the software is in terms of unit tests. In case you haven't done it just run ```mvn cobertura:cobertura``` and open ```target/site/cobertura/index.html```. No need to add plugins to pom.xml.

I bumped into your ```FastMath``` class too which I might use to speed up a few bits of performance important code. Thanks!

**Comment by EdwardRaff** [comment]
>I plugged away yesterday and saw that it was way easier than I had thought to use the Apache Spark ML libraries. ...  As this is or will be a path well-trodden it's probably a good way for me to go for the moment. 

Apache Spark is turning into a great project, and I have a few plans to contribute to it as well. If you need support that is probably a better option for you. 

Just some general advice though, the nature of Spark's intended scale means certain algorithms probably won't get implemented in it - or make make sacrifices that wouldn't be needed for smaller scale data sets. If you can't get the results you need with Spark, there may still be better algorithms you haven't tried simply because they aren't (and potential wont) be implemented in it. 

>By the way I see why tests are skipped by default! They took 3.5 hours to run on my crappy laptop

Thats... not what I expected! Test only take 1-3 minutes depending on which of my machines I run. I have them disabled simply because I have a habit of compiling and then running one quick test, and I didn't want to wait a minute after every compile for all tests to run.  What are you running on? Is there one test taking longer than all the others? 

>Have you run that yourself? Might be worth publishing on your github.io repo pointed to by JSAT readme as an indicator of how tested the software is in terms of unit tests.

I have not. When I originally started JSAT I didn't not plan on how big it would get, it was just me messing around and learning - so I didn't bother. I've tried to be better about it since. 

>I bumped into your FastMath class too which I might use to speed up a few bits of performance important code. Thanks!

Not a problem!

**Comment by davidmoten** [comment]
>Just some general advice though, the nature of Spark's intended scale means certain algorithms probably won't get implemented in it - or may make sacrifices that wouldn't be needed for smaller scale data sets. If you can't get the results you need with Spark, there may still be better algorithms you haven't tried simply because they aren't (and potential wont) be implemented in it.

Thanks for the advice.

>Thats... not what I expected! Test only take 1-3 minutes depending on which of my machines I run. I have them disabled simply because I have a habit of compiling and then running one quick test, and I didn't want to wait a minute after every compile for all tests to run. What are you running on? Is there one test taking longer than all the others?

I see what the issue was. The tests run fine in 1.5 minutes but cobertura instruments the classes in the test phase if cobertura is enabled and makes it last heaps longer (must be some busy code in your test).

A quick suggestion would be to leave tests enabled in the project by default so that people downloading the source don't have to poke around to get the tests to run. A nice addition for open source these days is free continuous integration for open source from Travis for example. Then someone can tell at a glance if the project is passing its unit tests. For example see https://github.com/davidmoten/rtree/blob/master/README.md.

**Comment by EdwardRaff** [comment]
>A quick suggestion would be to leave tests enabled in the project by default so that people downloading the source don't have to poke around to get the tests to run.

Yea, I see that now. I'll look into making netbeans altering its behavior and letting the normal pom have it enabled. I only just recently converted the project to maven after moving it out of google code (hence why it doesn't follow the standard maven structure).
