### ISSUE TITLE
license

### ISSUE THREAD

**Issue by richardhundt** [EdwardRaff/JSAT#29]
Hi,

I've just stumbled on your project while looking for an alternative to Weka. Frankly, this looks amazing and exactly what we need... until I realised that the reason I was looking for an alternative to Weka in the first place (besides its other shortcomings); the fact that it's GPL - means we can't use your library either, to put models into production.

So I was wondering if you've given any thought to switching from GPL to LGPL, or even something more permissive, like MIT, BSD or Apache licences?

**Comment by EdwardRaff** [comment]
I appreciate your interest and kind words! Please don't take this rudely, as I receive this question a lot. So I am replying for others to read as well. 

>the fact that it's GPL - means we can't use your library either, to put models into production.

You likely can use the GPL - you just don't *want* to use the GPL because of the constraints that it applies. That is completely understandable and fine, and part of the reason *why* I chose the GPL license. 

To expand on that statement, and address your follow up. I work on JSAT in my free time for no compensation for several years now. I've put a lot of effort into it, and even more effort that is not visible in the commits for things that I tried implementing and didn't work, or original prototype code that was ugly and cleaned up before implementing, and many hours of research, benchmarking, reading papers, and trial and error. 

Therefore, my personal compensation, is that others who make use of my code/work share their work too (as required by the GPL).  For this reason, I will not publicly release JSAT under any license more permissive than the GPL. 

As mentioned on the project page, if the GPL doesn't work for you - you may contact me privately about an alternative license. To make the implication explicit, this would entail us coming to a licensing agreement where I am compensated for my work - and you receive a license without the constraints of the GPL. I had no intention of making money off of JSAT - it's simply my personal belief and philosophy of sharing my hard work publicly.

**Comment by richardhundt** [comment]
Hi, thanks for your response.

Actually, you know, I do find your tone a little offensive. Please don't assume I'm a fool. I really _cannot_ use anything with a GPL license. Our software is provided in binary form, and installed on a client's infrastructure. If we link to your library, we will need to give the source code away too.

Regarding the amount of work involved. If you look at my own github profile, you'll see that I know what it takes to create open source software. Obviously you're free to license it any way you choose, and I'm free to use Python instead.

Take care.
