### ISSUE TITLE
Defaults for Classifiers/Regressors

### ISSUE THREAD

**Issue by camdirigo** [EdwardRaff/JSAT#30]
Hello all,
Would it be possible to have a wiki entry that lists the default parameters that should be used with each of the classifiers/regressors? It is not clear from the source code what those parameter values should be. Thanks!

**Comment by EdwardRaff** [comment]
Classifier with reasonable default parameters already have (or should) constructors that fill in the options for you. Otherwise use the `guess` methods of the class to determine a reasonable distribution to search from.

**Comment by camdirigo** [comment]
Thanks for the rapid reply, Edward. I have no problem with using a default constructor for classifiers such as NaiveBayes() and NewGLMNET(), but this does not seem to be the case with Kernel-based classifiers. For instance, I am trying to construct a Forgetron, but it requires the parameters KernelTrick kernel and int budget. These options do not appear to fill in for me. I attempted to construct a KernelTrick object like KernelTrick kernel = new KernelTrick(), but was not able to instantiate the object in this way. Could you please provide insight into this situation?

**Comment by EdwardRaff** [comment]
As I said, those do not have no-arg constructors because *there is no reasonable default value*. Such things usually require a hyper-parameter search. 

JSAT provides help to make that easier, with the Grid/Random search objects - and can auto-populate some parameters based on the aforementioned `guess` methods some classes have. See this [blog post](http://jsatml.blogspot.com/2015/07/easier-hyperparameter-tuning.html) for some details, but if you don't understand Machine Learning well you need to be especially careful not to over-fit using these methods.

**Comment by camdirigo** [comment]
Thanks for directing me to your hyperparameter example. By looking at the example, I figured out KernelTrick objects need to be declared as a parameter with the following syntax: 
Classifier classifier = new Forgetron(new RBFKernel(),500);

I will refer back to the original papers to determine the parameters as well as via grid search. Thanks again.
